/*
 * am_keys_codes.h
 *
 *  Created on: Mar 7, 2025
 *      Author: bartosz
 */

#ifndef AIRMOUSE_AM_KEYS_CODES_H_
#define AIRMOUSE_AM_KEYS_CODES_H_

enum {
	KEY_MOUSE_L = 			1 << 0,
	KEY_MOUSE_R = 			1 << 1,
	KEY_MOUSE_M = 			1 << 2,
	KEY_MOUSE_FWD = 		1 << 3,
	KEY_MOUSE_BCK = 		1 << 4,
	KEY_MOUSE_WHEELUP = 	1 << 5,
	KEY_MOUSE_WHEELDN = 	1 << 6,
	KEY_MOUSE_DPI = 		1 << 7,
	KEY_MOUSE_HOME = 		1 << 8,
	KEY_MOUSE_PRC = 		1 << 9
};

enum {
	KEY_QWERTY_1,
	KEY_QWERTY_2,
	KEY_QWERTY_3,
	KEY_QWERTY_4,
	KEY_QWERTY_5,
	KEY_QWERTY_6,
	KEY_QWERTY_7,
	KEY_QWERTY_8,
	KEY_QWERTY_9,
	KEY_QWERTY_0,
	KEY_QWERTY_Q,
	KEY_QWERTY_W,
	KEY_QWERTY_E,
	KEY_QWERTY_R,
	KEY_QWERTY_T,
	KEY_QWERTY_Y,
	KEY_QWERTY_U,
	KEY_QWERTY_I,
	KEY_QWERTY_O,
	KEY_QWERTY_P,
	KEY_QWERTY_A,
	KEY_QWERTY_S,
	KEY_QWERTY_D,
	KEY_QWERTY_F,
	KEY_QWERTY_G,
	KEY_QWERTY_H,
	KEY_QWERTY_J,
	KEY_QWERTY_K,
	KEY_QWERTY_L,
	KEY_QWERTY_ENTER,
	KEY_QWERTY_LSHIFT,
	KEY_QWERTY_Z,
	KEY_QWERTY_X,
	KEY_QWERTY_C,
	KEY_QWERTY_V,
	KEY_QWERTY_B,
	KEY_QWERTY_N,
	KEY_QWERTY_M,
	KEY_QWERTY_RSHIFT,
	KEY_QWERTY_UP,
	KEY_QWERTY_LCTRL,
	KEY_QWERTY_FN,
	KEY_QWERTY_LGUI,
	KEY_QWERTY_LALT,
	KEY_QWERTY_SPACE,
	KEY_QWERTY_RALT,
	KEY_QWERTY_LEFT,
	KEY_QWERTY_DOWN,
	KEY_QWERTY_RIGHT
};

#endif /* AIRMOUSE_AM_KEYS_CODES_H_ */
